"""
This script creates an easy-to-use distribution of the project.

This will only work so long as just the JS files are needed for distribution, so
I'll have to change it if appsscript.json needs changes.
"""
import pathlib



def catgs():
    jsFiles = getJsFilesFrom("src")
    globs = (makeGlob(file) for file in jsFiles)
    concatinated = makeHeader()
    for glob in globs:
        concatinated += glob
    with open("Code.js", "w") as outFile:
        outFile.write(concatinated)


def getJsFilesFrom(folder):
    paths = pathlib.Path(folder).glob("**/*.js")
    return paths


def makeGlob(file):
    content = f'// glob of {file.stem}\n'
    with open(file, "r") as f:
        for line in f:
            line = line.rstrip()
            if line is not "":
                content += line + '\n'
    return content

def makeHeader():
    return "// This file has been generated by catgs.py\n"


if __name__ == "__main__":
    catgs()